import "./globals.css";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { useAuthUser } from "@/lib/auth";
import { Header } from "@/components/header";
import { Spinner } from "@/components/ui/spinner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moo Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <Header />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
